version: "3"
services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    ports:
      - "8000:8000"
    command: python myfacebook/manage.py runserver 0.0.0.0:8000
    links:
      - db:db
    tty: true
    stdin_open: true
  db:
    build: ./db
    volumes:
      - ./db/datadir:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev_myfacebook_pw
      - MYSQL_DATABASE=dev_myfacebook_db
